//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPingInfoView.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCPingInfoView.I18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 _Exit 的本地化字符串。
        /// </summary>
        public static string ExitMenuItem_Header {
            get {
                return ResourceManager.GetString("ExitMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _File 的本地化字符串。
        /// </summary>
        public static string FileMenuItem_Header {
            get {
                return ResourceManager.GetString("FileMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host name 的本地化字符串。
        /// </summary>
        public static string HostnameColumn_HeaderText {
            get {
                return ResourceManager.GetString("HostnameColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index 的本地化字符串。
        /// </summary>
        public static string IndexColumn_HeaderText {
            get {
                return ResourceManager.GetString("IndexColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP Address 的本地化字符串。
        /// </summary>
        public static string IpColumn_HeaderText {
            get {
                return ResourceManager.GetString("IpColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latency 的本地化字符串。
        /// </summary>
        public static string LatencyColumn_HeaderText {
            get {
                return ResourceManager.GetString("LatencyColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Load 的本地化字符串。
        /// </summary>
        public static string LoadMenuItem_Header {
            get {
                return ResourceManager.GetString("LoadMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Segoe UI 的本地化字符串。
        /// </summary>
        public static string MetroFontFamily {
            get {
                return ResourceManager.GetString("MetroFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string PortColumn_HeaderText {
            get {
                return ResourceManager.GetString("PortColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protocol 的本地化字符串。
        /// </summary>
        public static string ProtocolColumn_HeaderText {
            get {
                return ResourceManager.GetString("ProtocolColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        public static string RemarkColumn_HeaderText {
            get {
                return ResourceManager.GetString("RemarkColumn_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Save 的本地化字符串。
        /// </summary>
        public static string SaveMenuItem_Header {
            get {
                return ResourceManager.GetString("SaveMenuItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Show Main Window 的本地化字符串。
        /// </summary>
        public static string ShowMenuItem_Header {
            get {
                return ResourceManager.GetString("ShowMenuItem_Header", resourceCulture);
            }
        }
    }
}
